services:
  notepad:
    container_name: notepad
    image: gamutakayama/notepad:latest
    environment:
      # UPLOAD_MAX_FILESIZE: 10M
      # POST_MAX_SIZE: 40M
      # MAX_EXECUTION_TIME: 150
      SITE_TITLE: ""
      PRIVATE_MODE: ""
      USER_ID: ""
      USERNAME: ""
      PASSWORD: ""
      JWT_KEY: ""
      HOSTED_ON: ""
      HOSTED_ON_URL: ""
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHAT_ID: ""
    restart: unless-stopped
    ports:
      - "10000:80"
    volumes:
      - ./_notes:/var/www/html/_notes
